name: SimpleWarp
version: '${project.version}'
main: me.liamsnow.simplewarp.SimpleWarp
api-version: 1.19
authors: [ LiamSnow ]
website: https://liamsnow.com
depend: [GriefPrevention]
softdepend: [WorldGuard]
commands:
  sethome:
    description: Sets your home location that can be teleported to from Spawn.
    usage: /<command>
    default: true
  stuck:
    description: Teleports you out of a hole if you are trapped in someone else's territory or Spawn.
    usage: /<command>
    aliased: [unstuck]
    default: true
  simplewarp-reload:
    description: Reloads the config & database for SimpleWarp.
    usage: /<command>
    aliases: [sw-reload]
    default: op
  simplewarp-setspawn:
    description: Sets the spawn for SimpleWarp.
    usage: /<command>
    aliases: [ sw-setspawn ]
    default: op
  simplewarp-setwarplobby:
    description: Sets the warp lobby for SimpleWarp.
    usage: /<command>
    aliases: [ sw-setwarplobby ]
    default: op
  simplewarp-givewarplobbysign:
    description: Gives player the special warp lobby sign.
    usage: /<command>
    aliases: [ sw-givewarplobbysign ]
    default: op

