name: SimpleWarp
version: '${project.version}'
main: me.liamsnow.simplewarp.SimpleWarp
api-version: 1.19
authors: [ LiamSnow ]
website: https://liamsnow.com
depend: []
softdepend: []
commands:
  warp-set-location:
    description: Sets the location for a warp
    usage: /<command>
    aliased: []
    default: op
  warp-
