name: SimpleSignWarp
version: '${project.version}'
main: me.liamsnow.simplesignwarp.SimpleSignWarp
api-version: 1.19
authors: [ LiamSnow ]
website: https://liamsnow.com
depend: []
softdepend: []
commands:
  warp-reload:
    description: Reloads config & data for SimpleSignWarp
    usage: /<command>
    aliased: [ ]
    default: op
  warp-set-location:
    description: Sets the location for a warp
    usage: /<command>
    aliased: []
    default: op
  warp-list:
    description: List all warps
    usage: /<command>
    aliased: []
    default: op
  warp-delete:
    description: Deletes a warp
    usage: /<command>
    aliased: [ ]
    default: op
  warp-get-sign:
    description: Gives you a sign that lets players use the warp
    usage: /<command>
    aliased: [ ]
    default: op

